name: app
description: Bachelors engineering thesis work

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  camera: ^0.10.0+3
  app_settings: ^4.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

  freezed: ^2.2.0
  flutter_gen_runner:
  flutter_gen: ^5.0.2
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
